require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '14.4'

target 'FindDifferences' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'FindDifferencesTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'FindDifferences-tvOS' do
  # Pods for FindDifferences-tvOS

  target 'FindDifferences-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end